### ISSUE TITLE
Message Request Object buildfrom getting stuck

### ISSUE THREAD

**Issue by sowgali** [GetStream/stream-chat-java#126]
I was trying to build a messageRequestObject from the Message Object as follows:
`Message message = Message.get(transaction.getMessageId()).request().getMessage();`
`Message.MessageRequestObject messageRequestObject = Message.MessageRequestObject.buildFrom(message);`
However, the thread is getting stuck in the second line. I am unsure why this is happening, could you help me understand if this is a mistake from my end or a bug?
**Edit:** I am getting the message from the first line, and I was able to print it, the problem is in line 2

**Comment by shaljam** [comment]
Closing the old issue. Feel free to re-open if you still have an issue.
