### ISSUE TITLE
I can't get messages sent to a channel using the java sdk. #145

### ISSUE THREAD

**Issue by realninety5** [GetStream/stream-chat-java#129]
Hello getstream, I am having a problem getting messages sent to a channel using the java sdk. When I call '.getMembers()', I get the list of members, but when I call '.getMessages()', it always returns an empty list even though there are messages in it.

**Comment by shaljam** [comment]
Hi @realninety5.
Make sure to include `state(true)` to get messages when getting the channel.
```
ChannelGetResponse channel = Channel.getOrCreate(testChannel.getType(), testChannel.getId())
      .state(true)
      .request();
Assertions.assertEquals(channel.getMessages().size(), 1);
```
Let me know how that went.
