### ISSUE TITLE
Cannot parse response from GetStream, looks like "invisible" in response is null

### ISSUE THREAD

**Issue by BolkunetsAlexandr** [GetStream/stream-chat-java#148]
threw exceptioncom.fasterxml.jackson.databind.JsonMappingException: invisible is marked non-null but is null\n at [Source: (okhttp3.ResponseBody$BomAwareReader); line: 1, column: 5391] (through reference chain: io.getstream.chat.java.models.Channel$ChannelPartialUpdateResponse[\"members\"]->java.util.ArrayList[0]->io.getstream.chat.java.models.Channel$ChannelMember[\"user\"]->io.getstream.chat.java.models.User[\"invisible\"])invisible is marked non-null but is null\n at [Source: (okhttp3.ResponseBody$BomAwareReader); line: 1, column: 5391] (through reference chain: io.getstream.chat.java.models.Channel$ChannelPartialUpdateResponse[\"members\"]->java.util.ArrayList[0]->io.getstream.chat.java.models.Channel$ChannelMember[\"user\"]->io.getstream.chat.java.models.User[\"invisible\"])invisible is marked non-null but is null"}}

Same issue on Message.search() // using postman

https://chat.stream-io-api.com/search?api_key=*******&payload={"query":null,"filter_conditions":{"id":"951d954e-e971-4dad-8422-79256cec3eb4","type":"REQUEST"},"message_filter_conditions":{"meetCard":{"$exists":false}},"limit":1,"offset":null,"next":null,"sort":[]}

![image](https://github.com/user-attachments/assets/02931be4-30c9-47d1-a1d9-832c2245e929)

UPD: sdk version "io.getstream:stream-chat-java:1.24.0", but it seems like a backward incompatible change made to the Stream API backend

**Comment by Djei** [comment]
This issue is also affecting our production environment. 
This does not look like an SDK bug though and more of a backward incompatible change made to the Stream API backend.

**Comment by BolkunetsAlexandr** [comment]
Seems like a fixed issue.
