### ISSUE TITLE
Send waveform_data for audio attachment

### ISSUE THREAD

**Issue by tkrason** [GetStream/stream-chat-java#152]
Hello,

We are using the server SDK for sending voice messages into message channel, and I would like to send `waveform_data` with attachment, so frontend can properly show them to user. Would it be possible to add support for this field?

Or is there anything else you would recomment for this use case?
Thank you.

**Comment by shaljam** [comment]
Hi, could you please elaborate on the `waveform_data`? You can already [set custom fields on attachments](https://getstream.github.io/stream-chat-java/io/getstream/chat/java/models/Message.Attachment.html#setAdditionalField(java.lang.String,java.lang.Object)). Do you need anything else?

**Comment by tkrason** [comment]
Hi thank you for the answer! 

In the end I used the mentioned custom fields, so I'm closing this.
