### ISSUE TITLE
System property typo in README

### ISSUE THREAD

**Issue by mhball** [GetStream/stream-chat-java#71]
In your README.md, under [getting-started](https://github.com/GetStream/stream-chat-java#-getting-started) it says the system property for setting the secret key is `io.getstream.chat.secretKey` but in the [DefaultClient](https://github.com/GetStream/stream-chat-java/blob/8bbecbab1dbc6c48ccd82d3a613c88abba4697db/src/main/java/io/getstream/chat/java/services/framework/DefaultClient.java#L25) it's reading `io.getstream.chat.apiSecret`.

**Comment by peterdeme** [comment]
https://github.com/GetStream/stream-chat-java/pull/73
