### ISSUE TITLE
FilterCondition invalid operation

### ISSUE THREAD

**Issue by samuelmasuebbc** [GetStream/stream-chat-java#86]
https://github.com/GetStream/stream-chat-java/blob/7f10ca4f4aa71733bd58fc55d7df68617531ef75/src/main/java/io/getstream/chat/java/models/FilterCondition.java#L53

The dollar sign is missing in the line above, causing exception using the FilterCondition lessThan.

It should be the following: 

```java   
return Collections.singletonMap(fieldName, Collections.singletonMap("$lt", fieldValue));
```

**Comment by ferhatelmas** [comment]
Good catch, thanks. Thanks fixed in #87
