### ISSUE TITLE
Channel last_message_at wrongly annotated with not nul

### ISSUE THREAD

**Issue by samuelmasuebbc** [GetStream/stream-chat-java#89]
Hello,

I found a minor bug. The channel field `last_message_at` is annotated with @NotNull, it can actually be null on channels with no message.

https://github.com/GetStream/stream-chat-java/blob/81b02e8f185167b48a26fc6f3c45e3451cccc229/src/main/java/io/getstream/chat/java/models/Channel.java#L98

The bug seems very minor but makes static code analysis fail, so it would be nice if it gets fixed :)

**Comment by ferhatelmas** [comment]
Another good catch 👍🏻
