### ISSUE TITLE
React frontend with Java Backend

### ISSUE THREAD

**Issue by KrunchMuffin** [GetStream/stream-chat-java#98]
What is the best method to transparently log a user into the frontend that is already logged in on the backend?

**Comment by ferhatelmas** [comment]
Back-end technology is irrelevant in general. 
Client should get a jwt token from your back-end if authenticated (this totally depends on your application) and set the user on it https://getstream.io/chat/docs/react/init_and_users/?language=javascript#connecting-the-user.
